version: '3.8'

services:
  web:
    image: boot-camp:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis
  
  db:
    platform: "linux/amd64"
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
  
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
    - '6379:6379'
    # volumes:
    # - redis-data:/data
    environment:
    - REDIS_ARGS=--requirepass root --appendonly yes
    restart: unless-stopped

volumes:
  dbdata:
